### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: org.leadpony.justify.internal.schema.SchemaReference cannot be cast to org.leadpony.justify.internal.schema.BasicSchema

### ISSUE THREAD

**Issue by avstp** [leadpony/justify#2] opened 2019-01-30 09:20 UTC
Hello! I was following instructions from front page here
```
// Reads the JSON schema
JsonSchema jsonSchema = service.readSchema(Thread.currentThread().getClass().getResourceAsStream("/json/schema.json"), Charset.forName("UTF-8"));
```
 And got exception:
```
Exception in thread "main" java.lang.ClassCastException: org.leadpony.justify.internal.schema.SchemaReference cannot be cast to org.leadpony.justify.internal.schema.BasicSchema
	at org.leadpony.justify.internal.schema.io.Draft07SchemaReader.makeIdentifiersAbsolute(Draft07SchemaReader.java:1038)
	at org.leadpony.justify.internal.schema.io.Draft07SchemaReader.lambda$makeIdentifiersAbsolute$1(Draft07SchemaReader.java:1046)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.leadpony.justify.internal.schema.io.Draft07SchemaReader.makeIdentifiersAbsolute(Draft07SchemaReader.java:1046)
	at org.leadpony.justify.internal.schema.io.Draft07SchemaReader.makeIdentifiersAbsoluteFromRoot(Draft07SchemaReader.java:1032)
	at org.leadpony.justify.internal.schema.io.Draft07SchemaReader.postprocess(Draft07SchemaReader.java:1023)
	at org.leadpony.justify.internal.schema.io.Draft07SchemaReader.read(Draft07SchemaReader.java:131)
	at org.leadpony.justify.api.JsonValidationService.readSchema(JsonValidationService.java:138)
```

**Comment by leadpony** [comment] 2019-01-30 11:18
Hello @avstp 
Thank you for reporting an issue.
I have added a test case to reproduce the reported problem in the last commit.
Your schema has a JSON object which contains both $ref and $id keywords doesn't it?
The problem is fixed in the next release.

**Comment by avstp** [comment] 2019-01-30 12:55
Thank you @leadpony !
Yes, it has 
```
"counterparty": {
      "$id": "#/properties/counterparty",
      "type": "string",
      "title": "The Counterparty Schema",
      "default": "",
      "examples": [
        "string"
      ],
      "$ref": "#/definitions/nonEmptyWithAvailableCharacters"
    }
```

**Comment by leadpony** [comment] 2019-01-31 11:57
Thank @avstp  for your prompt reply.
There is little notice.
The Draft-07 specification says

> All other properties in a "$ref" object MUST be ignored. 

So the "type" keyword in the schema above does not apply actually.
The schema at  "#/definitions/nonEmptyWithAvailableCharacters"
should have "type" keyword instead.
This behaviour may be changed in the upcoming Draft-08.

**Comment by leadpony** [comment] 2019-02-08 13:22
The lastest release published today fixed this issue. Thank you so much !

**Closed** 2019-02-08 13:22 UTC
Labels: bug
